# -*- coding: utf-8 -*-
"""ultra_simple_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzoIajq992UhhvDfc_8vA0OLfph3udnv
"""

#!/usr/bin/env python3

from ryu.base import app_manager
from ryu.controller import ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, MAIN_DISPATCHER, set_ev_cls
from ryu.ofproto import ofproto_v1_3
from ryu.lib.packet import packet, ethernet, ipv4
import time
from collections import defaultdict

class UltraSimpleDetector(app_manager.RyuApp):
    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]

    def __init__(self, *args, **kwargs):
        super(UltraSimpleDetector, self).__init__(*args, **kwargs)

        self.packet_counts = defaultdict(int)
        self.last_reset = time.time()

        # ADJUSTED: 30 pps threshold
        self.THRESHOLD = 30  # packets per second
        self.blacklisted = set()

        self.logger.info("DDoS Detector Started!")

    @set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev):
        datapath = ev.msg.datapath
        self.logger.info("Switch connected")

        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        match = parser.OFPMatch()
        actions = [parser.OFPActionOutput(ofproto.OFPP_CONTROLLER,
                                          ofproto.OFPCML_NO_BUFFER)]
        self.add_flow(datapath, 0, match, actions)

    def add_flow(self, datapath, priority, match, actions, buffer_id=None):
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser

        inst = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS,
                                             actions)]
        if buffer_id:
            mod = parser.OFPFlowMod(datapath=datapath, buffer_id=buffer_id,
                                    priority=priority, match=match,
                                    instructions=inst)
        else:
            mod = parser.OFPFlowMod(datapath=datapath, priority=priority,
                                    match=match, instructions=inst)
        datapath.send_msg(mod)

    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def _packet_in_handler(self, ev):
        msg = ev.msg
        datapath = msg.datapath
        pkt = packet.Packet(msg.data)

        ip_pkt = pkt.get_protocol(ipv4.ipv4)

        if ip_pkt:
            src_ip = ip_pkt.src

            # Whitelist check
            if src_ip in self.whitelist:
                self.flood_packet(msg, datapath)
                return

            # Blacklist check
            if src_ip in self.blacklisted:
                self.logger.warning("🚫 BLOCKED: %s", src_ip)
                return

            # Simple counting
            current_time = time.time()
            if current_time - self.last_reset > 1.0:  # Reset every second
                self.packet_counts.clear()
                self.last_reset = current_time

            self.packet_counts[src_ip] += 1

            # Simple detection - 30 pps threshold
            if self.packet_counts[src_ip] > self.THRESHOLD:
                self.logger.error("🚨 DDoS DETECTED FROM %s! (%d pps)",
                                src_ip, self.packet_counts[src_ip])
                self.block_attacker(src_ip, datapath)
            else:
                # Log traffic for visibility (only show if > 15 pps to reduce noise)
                if self.packet_counts[src_ip] > 15:
                    self.logger.info("📊 %s: %d pps", src_ip, self.packet_counts[src_ip])

        self.flood_packet(msg, datapath)

    def flood_packet(self, msg, datapath):
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        in_port = msg.match['in_port']

        actions = [parser.OFPActionOutput(ofproto.OFPP_FLOOD)]
        data = None
        if msg.buffer_id == ofproto.OFP_NO_BUFFER:
            data = msg.data

        out = parser.OFPPacketOut(datapath=datapath, buffer_id=msg.buffer_id,
                                  in_port=in_port, actions=actions, data=data)
        datapath.send_msg(out)

    def block_attacker(self, src_ip, datapath):
        if src_ip not in self.blacklisted:
            self.blacklisted.add(src_ip)
            self.logger.critical("🛡️ BLOCKING %s", src_ip)

            parser = datapath.ofproto_parser
            match = parser.OFPMatch(eth_type=0x0800, ipv4_src=src_ip)
            self.add_flow(datapath, 10, match, [])