# -*- coding: utf-8 -*-
"""ddos_topo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueqF9cK6R6hIxThXlGa7fV4Nt2ebeulC
"""

from mininet.topo import Topo
from mininet.node import OVSKernelSwitch, RemoteController
from mininet.net import Mininet
from mininet.cli import CLI
from mininet.log import setLogLevel

class DDoSTopo(Topo):
    def build(self):
        s1 = self.addSwitch('s1')
        attacker1 = self.addHost('attacker1', ip='10.0.0.2/24')
        attacker2 = self.addHost('attacker2', ip='10.0.0.3/24')
        legit = self.addHost('legit', ip='10.0.0.4/24')
        server = self.addHost('server', ip='10.0.0.5/24')

        self.addLink(attacker1, s1)
        self.addLink(attacker2, s1)
        self.addLink(legit, s1)
        self.addLink(server, s1)

def run():
    topo = DDoSTopo()
    net = Mininet(topo=topo,
                  controller=lambda name: RemoteController(name, ip='127.0.0.1'),
                  switch=OVSKernelSwitch,
                  autoSetMacs=True)
    net.start()
    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    run()