# -*- coding: utf-8 -*-
"""simple_working_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GknaYnKQWZoWJF8ANWuqQSG1BPvDBCXx
"""

#!/usr/bin/env python3

import time
from mininet.net import Mininet
from mininet.topo import Topo
from mininet.node import OVSKernelSwitch, RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel, info

class SimpleTopo(Topo):
    def build(self):
        s1 = self.addSwitch('s1')

        hosts = [
            ('attacker1', '10.0.0.2'),
            ('attacker2', '10.0.0.3'),
            ('legit', '10.0.0.4'),
            ('server', '10.0.0.5')
        ]

        for name, ip in hosts:
            host = self.addHost(name, ip=ip+'/24')
            self.addLink(host, s1)

def simple_test(net):
    """Simple test without threading issues"""
    info('*** 🚀 DDoS Protection Test (30 pps threshold)\n')

    server = net.get('server')
    attacker1 = net.get('attacker1')
    attacker2 = net.get('attacker2')
    legit = net.get('legit')

    # Start a reliable server
    info('*** Starting web server\n')
    server.cmd('pkill -f "python.*http.server"')
    server.cmd('python3 -m http.server 8080 > /dev/null 2>&1 &')
    time.sleep(3)

    def test_connectivity(host, name):
        """Test if host can reach server"""
        # Test ping
        ping_result = host.cmd('ping -c 2 -W 1 10.0.0.5')
        ping_ok = '64 bytes from' in ping_result

        # Test HTTP
        http_result = host.cmd('curl -s -w "%{http_code}" -o /dev/null --connect-timeout 3 http://10.0.0.5:8080')
        http_ok = '200' in http_result

        if ping_ok and http_ok:
            info(f'*** ✅ {name} - FULL connectivity\n')
            return 'FULL'
        elif ping_ok:
            info(f'*** ✅  {name} - Ping works\n')
            return 'PING_ONLY'
        else:
            info(f'*** ❌ {name} - COMPLETELY BLOCKED\n')
            return 'BLOCKED'

    info('*** 🧪 STEP 1: Initial connectivity test\n')
    legit_initial = test_connectivity(legit, 'Legitimate')
    attacker1_initial = test_connectivity(attacker1, 'Attacker1')
    attacker2_initial = test_connectivity(attacker2, 'Attacker2')

    info('\n*** 🔥 STEP 2: Starting DDoS attacks (target: >30 pps)\n')
    info('*** Attackers sending flood traffic...\n')

    # Start STRONGER attacks to reach 30+ pps
    attacker1.cmd('ping -c 200 -f 10.0.0.5 > /dev/null 2>&1 &')
    attacker2.cmd('ping -c 200 -f 10.0.0.5 > /dev/null 2>&1 &')
    # Add additional ping processes to ensure we hit 30+ pps
    attacker1.cmd('ping -c 200 -f 10.0.0.5 > /dev/null 2>&1 &')
    attacker2.cmd('ping -c 200 -f 10.0.0.5 > /dev/null 2>&1 &')

    info('*** ⏳ Waiting 10 seconds for detection...\n')
    time.sleep(10)

    info('\n*** 🧪 STEP 3: Testing legitimate traffic during attack\n')
    info('*** Legitimate host sending normal requests...\n')

    legit_successes = 0
    for i in range(5):
        result = legit.cmd('curl -s -w "%{http_code}" -o /dev/null --connect-timeout 3 http://10.0.0.5:8080')
        if '200' in result:
            info(f'*** ✅ Legitimate request {i+1}/5: SUCCESS\n')
            legit_successes += 1
        else:
            info(f'*** ❌ Legitimate request {i+1}/5: FAILED\n')
        time.sleep(2)

    info('*** ⏳ Waiting 10 more seconds for blocking...\n')
    time.sleep(10)

    info('\n*** 🧪 STEP 4: Final connectivity test\n')
    legit_final = test_connectivity(legit, 'Legitimate')
    attacker1_final = test_connectivity(attacker1, 'Attacker1')
    attacker2_final = test_connectivity(attacker2, 'Attacker2')

    info('\n*** 📊 FINAL RESULTS:\n')
    info(f'*** Legitimate host: {legit_successes}/5 requests successful\n')

    if legit_final in ['FULL', 'PING_ONLY']:
        info('*** ✅ SUCCESS: Legitimate host can still communicate!\n')
    else:
        info('*** ❌ FAILURE: Legitimate host was blocked!\n')

    if attacker1_final == 'BLOCKED' and attacker2_final == 'BLOCKED':
        info('*** ✅ SUCCESS: Both attackers were blocked!\n')
    elif attacker1_final == 'BLOCKED':
        info('*** ⚠️  PARTIAL: Attacker1 blocked, Attacker2 not blocked\n')
    elif attacker2_final == 'BLOCKED':
        info('*** ⚠️  PARTIAL: Attacker2 blocked, Attacker1 not blocked\n')
    else:
        info('*** ❌ FAILURE: No attackers were blocked!\n')
        info('*** 💡 Tip: Try increasing the number of ping processes\n')

    # Cleanup
    attacker1.cmd('pkill -f ping')
    attacker2.cmd('pkill -f ping')
    server.cmd('pkill -f http.server')

def main():
    setLogLevel('info')

    info('*** 🚀 Starting DDoS Protection Test (30 pps threshold)\n')
    info('*** Make sure RYU is running: ryu-manager ultra_simple_detector.py --verbose\n')

    topo = SimpleTopo()
    net = Mininet(topo=topo,
                  controller=lambda name: RemoteController(name, ip='127.0.0.1', port=6633),
                  switch=OVSKernelSwitch,
                  autoSetMacs=True)

    net.start()

    try:
        simple_test(net)

        info('\n*** 💡 Manual testing phase\n')
        info('*** Try these commands:\n')
        info('***   legit ping 10.0.0.5\n')
        info('***   legit curl http://10.0.0.5:8080\n')
        info('***   attacker1 ping 10.0.0.5\n')
        info('***   attacker2 ping 10.0.0.5\n')

        CLI(net)

    finally:
        net.stop()

if __name__ == '__main__':
    main()